### PR TITLE
oci-umount: use a ref to the old /proc/self in the new mnt ns

### PR DESCRIPTION
**Pull request by giuseppe**
Do not attempt to use /proc/self/ when entering the new mount
namespace as the hook might not have a mapping in the destination
/proc.  It is not a problem with runc as the new /proc is mounted
after the hooks are executed, but we should not rely on this behavior
as it is not mandated by the OCI specs.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
the issue can be easily duplicated with:
```
# unshare -mp --mount-proc -f sh -c 'sleep 1d' &
# nsenter -m -t $(pgrep -f 'sleep 1d') readlink -f /proc/self/
```

**Comment by giuseppe** [comment]
ping?

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
> It is not a problem with runc as the new /proc is mounted
after the hooks are executed
runc runs the hooks before the pivot root. All the mounts are already done by this point in the new mount namespace including the /proc.

**Comment by mrunalp** [comment]
The new proc is still at rootfs/proc before the pivot root. Are you addressing the case, when some runtime is running the hooks after its new /proc is mounted and pivot root is done? Many hooks rely on being called just before the pivot root but after the container mounts are done.

**Comment by giuseppe** [comment]
yes, I am trying to address the case where the hooks are launched after the pivot_root is done.  It seems like an assumption from the hooks on how runC works that I could not find specified in the specs.  Do you think this behaviour should be better specified in the OCI runtime specs?

**Comment by giuseppe** [comment]
FWIW: I've changed crun to behave like runC: https://github.com/giuseppe/crun/commit/8c18d6a00bda8ef8c3c682cf8a7ad35bd1a89cdc

**Comment by rhvgoyal** [comment]
Is this patch still required?

**Comment by giuseppe** [comment]
not for crun.  If it is safe to assume the prestart hooks are always called before the pivot_root (which I don't see specified in the OCI runtime), then we can close it.

**Comment by rhvgoyal** [comment]
If this is not a problem for anybody as of now, then lets close it. Once it becomes an issue for somebody, please open it. again.

**Pull request closed without merging**
