### PR TITLE
Add message to errors which fail hook run

### PR DESCRIPTION
**Pull request by ashcrow**
Add "Failing hook run" to error messages which cause the hook to fail.
Error messages which are skipped or shown for information only are left
alone.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
We already prefix string "error" in error messages using "pr_perror()" macro. And that makes it pretty clear that hook failed and it encountered an error. Otherwise it will be either info or warning.

So I am not convinced that we should add "Failing running hook" in each error message.

**Comment by ashcrow** [comment]
@rhvgoyal I understand. It's your call, but keep in mind it's also appended to errors which don't cause the hook to fail.

Here is an example:

```c
if (ret < 0) {
    pr_perror("Error while trying to map mount [%s] from host to conatiner. Skipping.\n", mounts_on_host[i]);
    continue;
}
```

**Comment by rhvgoyal** [comment]
@ashcrow May be we should change these skipping messages to pr_pwarning() instead of pr_perror().

**Comment by ashcrow** [comment]
@rhvgoyal sure, that works. I'll update this PR and move to that.

**Comment by ashcrow** [comment]
Closed in favor of https://github.com/projectatomic/oci-umount/pull/4

**Pull request closed without merging**
