### PR TITLE
Fix containers/storage mount point names

### PR DESCRIPTION
**Pull request by rhatdan**
Also add in /run/containers/storage as the place where shm is mounted.

### CODE REVIEW

**Comment by rhatdan** [comment]
@rhvgoyal PTAL

**Comment by rhvgoyal** [comment]
LGTM

Having said that, I think time has come that we should break down oci-umount.conf into smaller files and every package should drop list of its own mount points in say `/etc/oci-umount` dir. Currently we have 3 users. docker, docker-latest and crio. That way oci-umount will not try to unmount everything which does not exist and also there will be less crap in journal.

**Comment by rhatdan** [comment]
The way to do this is /etc/oci-umount.d
And drop each file there.  Then have crio/kpod and docker drop them.
Makes sense, but I think we should merge this for now, and I will open a pull request for that later.

**Comment by rhatdan** [comment]
BTW I will also be adding a pull request to add a config file to oci-umount, so that we only run the command if a user has bind mounts.

**Pull request merged**
